# Generated by Django 3.0 on 2024-12-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20241209_2311'),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('MID', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('Mname', models.CharField(max_length=32)),
                ('Account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Phone_number', models.CharField(max_length=32)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='Address',
        ),
    ]
