# Generated by Django 3.0 on 2024-12-10 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20241210_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Belong',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Merchant'),
        ),
    ]
