# Generated by Django 3.0 on 2024-12-10 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_product_belong'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_person',
            name='Account_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='delivery_person',
            name='Address',
            field=models.CharField(default='xxx', max_length=100),
        ),
        migrations.AddField(
            model_name='delivery_person',
            name='Dname',
            field=models.CharField(default='xxx', max_length=32),
        ),
    ]
