# Generated by Django 3.0 on 2024-12-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20241210_1127'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Passward',
            field=models.CharField(default='123456', max_length=32),
        ),
        migrations.AddField(
            model_name='delivery_person',
            name='Passward',
            field=models.CharField(default='123456', max_length=32),
        ),
        migrations.AddField(
            model_name='merchant',
            name='Passward',
            field=models.CharField(default='123456', max_length=32),
        ),
    ]
