# Generated by Django 3.0 on 2024-12-14 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20241210_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='DID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Delivery_Person'),
        ),
    ]
