# Generated by Django 3.0 on 2024-12-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.CharField(max_length=32, unique=True)),
                ('student_name', models.CharField(max_length=32)),
            ],
        ),
    ]
