# Generated by Django 3.0 on 2024-12-09 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('CID', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('Cname', models.CharField(max_length=32)),
                ('Account_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Phone_number', models.CharField(max_length=32)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Delivery_Person',
            fields=[
                ('DID', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('Phone_number', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OID', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('Status', models.CharField(max_length=32)),
                ('Date', models.CharField(max_length=32)),
                ('Payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('CID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('PID', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('Pname', models.CharField(max_length=32)),
                ('Price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('TID', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('Payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('Status', models.CharField(max_length=32)),
                ('DID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Delivery_Person')),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Order')),
            ],
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.AddField(
            model_name='order',
            name='PID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Product'),
        ),
    ]
